### ISSUE TITLE
Another useful link from GentooLTO

### ISSUE THREAD

**Issue by firasuke** [N-R-K/Ofast#5]
The GentooLTO project has the following [ltoworkarounds.conf](https://raw.githubusercontent.com/InBetweenNames/gentooLTO/master/sys-config/ltoize/files/package.cflags/ltoworkarounds.conf) file that includes an Ofast section with more packages listed.

**Comment by N-R-K** [comment]
Thank you, wasn't aware of that. I'll add them in after taking a deeper look.

**Comment by firasuke** [comment]
Glad I could help.
